#!/bin/bash
# /usr/bin/install-i3-theme

mkdir -p ~/.config/
mkdir -p ~/.local/share
cp -ra /etc/skel/.config/* ~/.config/
cp -ra /etc/skel/.local/share/* ~/.local/share/
echo "Installed  config to user profile"
